# Settings for the Deep NN classifier script
BATCH_SIZE: 32
CUDA: True
N_WORKERS: 0
SEED: 916

MULTI_MODEL_PLOT: False # network, model path & checkpoint hard-coded
DATASET_SIZE_PLOT: False

NETWORK: inceptionv3
OUTPUT_PATH: output/CASIA/exp04_cpd_slide_inceptionv3_Above_Conv2d4a_roi_cropped/
TEST_CHKPT: 450

TRAIN_IMG_DIR:
TEST_IMG_DIR: data/CASIA/flip/ROI/test/

ENLARGE_SIZE: 256
CROP_SIZE: 224
RESCALE_SIZE: 299

NUM_CLASSES: 1000
